version: '3.8'
services:
  db:
    image: postgres
    container_name: allobank-split-bill
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"